// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJyijDoXFPJiny127--EClhbU32zOIPU8',
    appId: '1:219569610883:web:e8b72507e32bf7a5a0fbb6',
    messagingSenderId: '219569610883',
    projectId: 'chat-f98be',
    authDomain: 'chat-f98be.firebaseapp.com',
    storageBucket: 'chat-f98be.appspot.com',
    measurementId: 'G-FNWY8EYQQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB_J2he06fLPRXM0BMcYtaT_JVUrPIDio',
    appId: '1:219569610883:android:e1df9e0e2a04a4c1a0fbb6',
    messagingSenderId: '219569610883',
    projectId: 'chat-f98be',
    storageBucket: 'chat-f98be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbW2iqF3hex4cKm3vmdmnAD85oOCtTQw8',
    appId: '1:219569610883:ios:472488cea7da0818a0fbb6',
    messagingSenderId: '219569610883',
    projectId: 'chat-f98be',
    storageBucket: 'chat-f98be.appspot.com',
    iosBundleId: 'com.example.flutterspod',
  );
}
